"""Add driver module

Revision ID: 6c1caed95851
Revises: 
Create Date: 2026-06-11 02:21:23.126023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1caed95851'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_category_id'), ['category_id'], unique=False)

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_driver_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_vehicles_assigned_driver_id'), ['assigned_driver_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['assigned_driver_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_vehicles_assigned_driver_id'))
        batch_op.drop_column('assigned_driver_id')

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_category_id'))

    # ### end Alembic commands ###
