from app.modules.vehicles.dto import VehicleDTO


def vehicle_to_dto(vehicle):
    return VehicleDTO(
        id=vehicle.id,
        company_id=vehicle.company_id,
        circle_id=vehicle.circle_id,
        client_id=vehicle.client_id,
        project_id=vehicle.project_id,
        subzone_id=vehicle.subzone_id,
        vehicle_number=vehicle.vehicle_number,
        vehicle_type=vehicle.vehicle_type,
        vehicle_category=vehicle.vehicle_category,
        vehicle_brand=vehicle.vehicle_brand,
        vehicle_model=vehicle.vehicle_model,
        manufacturing_year=vehicle.manufacturing_year,
        chassis_number=vehicle.chassis_number,
        engine_number=vehicle.engine_number,
        owner_name=vehicle.owner_name,
        owner_phone=vehicle.owner_phone,
        vendor_name=vehicle.vendor_name,
        vendor_contact=vehicle.vendor_contact,
        gps_enabled=vehicle.gps_enabled,
        realtime_tracking_enabled=vehicle.realtime_tracking_enabled,
        deployment_allowed=vehicle.deployment_allowed,
        attendance_linked=vehicle.attendance_linked,
        fuel_tracking_enabled=vehicle.fuel_tracking_enabled,
        geo_fencing_enabled=vehicle.geo_fencing_enabled,
        incident_monitoring_enabled=vehicle.incident_monitoring_enabled,
        maintenance_tracking_enabled=vehicle.maintenance_tracking_enabled,
        load_capacity=vehicle.load_capacity,
        passenger_capacity=vehicle.passenger_capacity,
        fuel_capacity=vehicle.fuel_capacity,
        operational_capacity=vehicle.operational_capacity,
        status=vehicle.status,
        insurance_status=vehicle.insurance_status,
        fitness_status=vehicle.fitness_status,
        permit_status=vehicle.permit_status,
        puc_status=vehicle.puc_status,
        verification_status=vehicle.verification_status,
        assigned_driver=vehicle.assigned_driver,
        current_deployment=vehicle.current_deployment,
    )

